### ISSUE TITLE
Implementation questions

### ISSUE THREAD

**Issue by vstath** [torden/php-mdbm#28]
Hi, 

I see you have multiple implementations for mdbm and I was wondering if they all perform more-or-less equally? Do you have any performance data? Also, is there any plans to have an openresty (nginx/lua) lib?

I saw you are very active with it so I thought I'd ask :-) I have not worked with mdbm or your implementations but I plan on doing so when I manage to find some time for playing around.

Thanks for your code

**Comment by torden** [comment]
Hi @vstath ,
first of all, they all equally perform and I developing simplify it as much as possible 

the following are performance data 

- Go-lang version: https://github.com/torden/go-mdbm#benchmark
- Python Version: https://github.com/torden/py-mdbm#benchmark-1

is it what I thinks it is? 

Unfortunately I have not a php-mdbm performance data but I looking for a performance testing framework.
and, I have several implementations plan. nginx is also included.
I will try, check out the openresty in the near future, if you can, please help for implementation :-)

Thanks

**Comment by vstath** [comment]
Thank you so much. Unfortunately I'm not a developer (especially not for such advanced things). Had I been, I would certainly code and commit. 

Openresty is powerful and can not just do HTTP/s but also native TCP/UDP servers (thus perhaps an easy to maintain implementation, language agnostic with all TLS handled by Openresty). If you made the Openresty/Lua version I could create examples and daemons to assist the community. 

For example I could demonstrate: Openresty HTTP endpoint(s) --> TCP (sharding / read load balancing) --> Openresty mdbm daemon backend(s) with failover and redundancy built in. 

Such an example could provide horizontal scaling (together with some automatic resharding) and it might be useful, especially in heavy HTTP sessioning and authentication scenarios. Again, it would be an infrastructure solution, language agnostic, with HTTP/websockets/TCP/unix socket interfaces available out of the box with TLS.

**Comment by vstath** [comment]
You can view an example implementation (for cjson library) here https://github.com/openresty/lua-cjson/

Perhaps may help familiarize more with how openresty/lua works

**Comment by torden** [comment]
I will check it up.
Thanks @vstath ,

**Comment by vstath** [comment]
Hello Torden,

just a heads up to check if you managed to look into this at all since. 

I'm around if you need to discuss about it or some sort of collaboration ;-)
