### ISSUE TITLE
Suggestion: change log level from E_ERROR to E_WARNING

### ISSUE THREAD

**Issue by shimashimashi** [torden/php-mdbm#38]
Current code halts the script on any error because its log level is E_ERROR(not recoverable).
```php
        php_error_docref(NULL TSRMLS_CC, E_ERROR, "failed to open the mdbm");
```
https://github.com/torden/php-mdbm/blob/master/src/mdbm.c#L1045

Could we use E_WARNING instead?
It is recoverable so users can handle errors.

**Comment by torden** [comment]
Hi @shimashimashi 

I saw the other modules about  opening function.
Your suggestion is Right, I will take this issue and change the E_ERROR to E_WARNING in mdbm_open as soon
Thx for your suggestion.
(Too Late. Quickly Following this issue)

**Comment by torden** [comment]
Hi @shimashimashi 
Could you plz check up laster version? I did change to E_WARNING
if you have any issue, plz feel free raise issue
Thanks & Best regards.

**Comment by shimashimashi** [comment]
Thank you!
